import { images } from "utils/statics/fakeDataComments";

export const MSG_LIST_1_2 = [
    {
        fromUserName: "اصغر فرهادی",
        fromurlImage: "",
        toUrlImage: "",
        toUserName: "جعفر کاظمی",
        from: 2,
        to: 1,
        msg: "سشسیبشسیبشسیبشسیبشسیب شسیبشسیبشسی شسیبشسیبس شسیبشسیلام بیستون بیستون",
        date: "1401/02/02 20:30",
    },
    {
        fromUserName: "اصغر فرهادی",
        fromurlImage: "",
        toUrlImage: "",
        toUserName: "جعفر کاظمی",
        from: 1,
        to: 2,
        msg: "سلام بیستون بیستون",
        date: "1401/02/02 20:30",
    },
    {
        fromUserName: "اصغر فرهادی",
        fromurlImage: "",
        toUrlImage: "",
        toUserName: "جعفر کاظمی",
        from: 1,
        to: 2,
        msg: "سلام بیستون بیستون",
        date: "1401/02/02 20:30",
    },
    {
        fromUserName: "اصغر فرهادی",
        fromurlImage: "",
        toUrlImage: "",
        toUserName: "جعفر کاظمی",
        from: 1,
        to: 2,
        msg: "سلام بیستون بیستون",
        date: "1401/02/02 20:30",
    },
    {
        fromUserName: "اصغر فرهادی",
        fromurlImage: "",
        toUrlImage: "",
        toUserName: "جعفر کاظمی",
        from: 1,
        to: 2,
        msg: "سلام بیستون بیستون",
        date: "1401/02/02 20:30",
    },
    {
        fromUserName: "اصغر فرهادی",
        fromurlImage: "",
        toUrlImage: "",
        toUserName: "جعفر کاظمی",
        from: 1,
        to: 2,
        msg: "سلام بیستون بیستون",
        date: "1401/02/02 20:30",
    },
    {
        fromUserName: "اصغر فرهادی",
        fromurlImage: "",
        toUrlImage: "",
        toUserName: "جعفر کاظمی",
        from: 1,
        to: 2,
        msg: "سلام بیستون بیستون",
        date: "1401/02/02 20:30",
    },
    {
        fromUserName: "اصغر فرهادی",
        fromurlImage: "",
        toUrlImage: "",
        toUserName: "جعفر کاظمی",
        from: 2,
        to: 1,
        msg: "سلام بیستون بیستون",
        date: "1401/02/02 20:30",
    },
    {
        fromUserName: "اصغر فرهادی",
        fromurlImage: "",
        toUrlImage: "",
        toUserName: "جعفر کاظمی",
        from: 1,
        to: 2,
        msg: "سلام بیستون بیستون",
        date: "1401/02/02 20:30",
    },
    {
        fromUserName: "اصغر فرهادی",
        fromurlImage: "",
        toUrlImage: "",
        toUserName: "جعفر کاظمی",
        from: 2,
        to: 1,
        msg: "سلام بیستون بیستون",
        date: "1401/02/02 20:30",
    },
];

export const MSG_LIST_1_3 = [
    {
        fromUserName: "اصغر فرهادی",
        type: "text",
        toUserName: "رضا کریمی",
        from: 3,
        to: 1,
        msg: "سشسیبشسیبشسیبشسیبشسیب شسیبشسیبشسی شسیبشسیبس شسیبشسیلام بیستون بیستون",
        date: "1401/02/02 20:30",
    },
    {
        fromUserName: "اصغر فرهادی",
        type: "text",
        toUserName: "رضا کریمی",
        from: 1,
        to: 3,
        msg: "سلام بیستون بیستون",
        date: "1401/02/02 20:30",
    },
    {
        fromUserName: "اصغر فرهادی",
        type: "text",
        toUserName: "رضا کریمی",
        from: 1,
        to: 3,
        msg: "سلام بیستون بیستون",
        date: "1401/02/02 20:30",
    },
    {
        fromUserName: "اصغر فرهادی",
        type: "text",
        toUserName: "رضا کریمی",
        from: 1,
        to: 3,
        msg: "سلام بیستون بیستون",
        date: "1401/02/02 20:30",
    },
    {
        fromUserName: "اصغر فرهادی",
        type: "text",
        toUserName: "رضا کریمی",
        from: 3,
        to: 1,
        msg: "سلام بیستون بیستون",
        date: "1401/02/02 20:30",
    },
    {
        fromUserName: "اصغر فرهادی",
        type: "text",
        toUserName: "رضا کریمی",
        from: 1,
        to: 3,
        msg: "سلام بیستون بیستون",
        date: "1401/02/02 20:30",
    },
    {
        fromUserName: "اصغر فرهادی",
        type: "text",
        toUserName: "رضا کریمی",
        from: 3,
        to: 1,
        msg: "سلام بیستون بیستون",
        date: "1401/02/02 20:30",
    },
    {
        fromUserName: "اصغر فرهادی",
        type: "text",
        toUserName: "رضا کریمی",
        from: 3,
        to: 1,
        msg: "سلام بیستون بیستون",
        date: "1401/02/02 20:30",
    },
    {
        fromUserName: "اصغر فرهادی",
        type: "image",
        toUserName: "رضا کریمی",
        from: 1,
        to: 3,
        msg: "سلام بیستون بیستون",
        imageContent:
            "https://images.unsplash.com/photo-1503023345310-bd7c1de61c7d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8aHVtYW58ZW58MHx8MHx8&w=1000&q=80",
        date: "1401/02/02 20:30",
    },
    {
        fromUserName: "اصغر فرهادی",
        type: "image",
        toUserName: "رضا کریمی",
        from: 3,
        to: 1,
        imageContent:
            "https://h5p.org/sites/default/files/h5p/content/1209180/images/file-6113d5f8845dc.jpeg",
        msg: "سلام بیستون بیستون",
        date: "1401/02/02 20:30",
    },
];
export const USER_LIST = [
    {
        userName: "اصغر فرهادی",
        id: 2,
        avatar: images[0],
        date: "20:30",
        unReadMsg: 2,
    },
    {
        userName: "رضا کریمی",
        id: 3,
        avatar: images[1],
        date: "1401/02/02",
        unReadMsg: 0,
    },
    {
        userName: "اصغر جاجی",
        id: 4,
        avatar: images[2],
        date: "15:30",
        unReadMsg: 0,
    },
    {
        userName: "رحیم فرهادی",
        id: 5,
        avatar: images[3],
        date: "1401/02/02",
        unReadMsg: 0,
    },
    {
        userName: "اصغر رضایی",
        id: 6,
        avatar: "",
        date: "14:25",
        unReadMsg: 4,
    },
];
