name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'npm'

    - name: Build
      run: docker build . -t ghcr.io/mjavadmt/saku:${{ github.sha }}

    - name: push
      run: |
        docker login --username=${{ secrets.REGISTRY_USERNAME }} --password=${{ secrets.PAT }} ghcr.io
        docker push ghcr.io/mjavadmt/saku:${{ github.sha }}

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    - name: Run Tests
      run: |
        docker login --username=${{ secrets.REGISTRY_USERNAME }} --password=${{ secrets.PAT }} ghcr.io
        export TAG=${{ github.sha }}
        docker pull ghcr.io/mjavadmt/saku:$TAG
        docker run -e CI=true ghcr.io/mjavadmt/saku:$TAG /bin/sh -c "npm test -- --coverage"